### ISSUE TITLE
Диверсификация бюджета киберФонда

### ISSUE THREAD

**Issue by 21xhipster** [cyberFund/org#14]
- [ ] @vitalylvov  - проанализировать варианты по переводу части средств в бюджете кибера и Сатоши из биткоинов в доллары с целью хэджирования рисков и обеспечения обязательных обязательств (инфраструктура, зп на текущий состав команды)
- [ ] @vitalylvov - представить предложения по диверсификации членам борда

**Comment by mastercyb** [comment]
@mguryeva I think current structure is diversified enough ;-)
