### ISSUE TITLE
Resolve ADSadly

### ISSUE THREAD

**Issue by xhipster** [cyberFund/org#2]
Выкупить долю у ADSadly или по-иному закрыть наши обязательства. Требуется восстановить хронологию и обещания, прийти к консенсусу и выкупить токены или по-иному закрыть текущую конфликтную ситуацию.

**Comment by ghost** [comment]
лол. ребята, это так не работает. Дима, он договривался с тобой конкретно. 
с его т.з. ты пропал со свззи. с Мариной он ни о чем не договаривался.
