### ISSUE TITLE
Our projects should not contradict our princples

### ISSUE THREAD

**Issue by mastercyb** [cyberFund/org#21]
Golosio is not following the principle of informational freedom declared by founders

**Comment by ghost** [comment]
хорошим шагом было бы не отмалчиваться на самой платформе, а использовать её для освещения движений, убеждать сомневающихся аргументами и т.п. 

пока что я пытаюсь убедить Виталю и Костю написать по постику про их видение ситуации. не как членов КФ а как делегатов из топ19.

**Comment by ghost** [comment]
https://goldvoice.club/tags/ru--khardfork/
https://goldvoice.club/tags/hardfork/
мне странно, что приходится объяснять такие вещи, но - нельзя так просто построить блог-платформу/ соц-сеть - и отмалчиваться. я понимаю, что это не про голосио в данном случае - но ты как бы фаундер и КФ тоже. Извини, но озвученная Мариной позиция - нам срать на сообщество, будем крутить как хочем, потому что можем, заткнитесь - не приведет к успеху. КФ следует вступить в диалог. На блокчейне. Ну, или пожинать плоды позже. 
Дима, изначально деньги собирались под DPoS-based блокчейн. Если концепция поменялась - дай пост на голосе. Если есть какие-то важные посты - дай ссылки. Если же система собирается оставаться тем, чем она была на момент, когда сотни людей поверили нам - будьте любезны вынуть головы из песка, прийти на площадку, и начать разговор. 


Народ там в чати удивился, что куда-то попропадли эфиры "вечер с голосом" с ютуба :)

**Comment by mastercyb** [comment]
Всему свое время. DPOS это как раз когда сообщество может самоорганизовываться. Пусть попробует это сделать само. Не совсем понимаю причем тут КФ. КФ уже давно даже снял голоса с делеагатов.

**Comment by ghost** [comment]
ты читал посты?

**Comment by ghost** [comment]
по тегам выше?

**Comment by tomarcafe** [comment]
и да - определитесь пожалуйста - Марина на митинге озвучила позицию КФ как ты тут намекаешь - или свою собственную - как Костя в чате пишет?

**Comment by litrbooh** [comment]
@21xhipster 
Я понять не могу, вы сами верите в то, что говорите, или все дружно театральный кружок закончили?

Ты послушай, если ещё не слышал, что директор Голоса - Марина заявляет: "мы считаем", "мы хотим", "мы решили", "мы не будет вводить линейность" и тп. На вопрос кто такие "мы", она прямо отвечает, что мы - это КФ и у нас есть большой стек голосов, чтобы решать. 
А теперь спрашиваешь при чем тут КФ? **Серьезно?**
Ссылка на видос тут: https://golos.blog/ru--delegaty/@litrbooh/my-khotim-my-reshili-my-schitaem-stop-it

Ваши же разработчики с вопросами отправляют в КФ:
![default](https://user-images.githubusercontent.com/22373216/32913194-a8608464-cb22-11e7-9905-d9cb17b22b2d.png)
